# Generated by Django 4.1.5 on 2023-01-03 02:16

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('coach', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('start_time', models.TimeField(help_text="\n        <details>\n        <summary>Specify when the class will <em>start</em> on scheduled days. Format: 'HH:mm:ss'</summary>\n        <br>\n        <p>This starting time applies to all scheduled days, and must be before the end time.</p>\n        <p>If you would like to specify an additional recurring timeslot, you must create another class for this studio.</p>\n        </details>\n    ")),
                ('end_time', models.TimeField(help_text="\n        <details>\n        <summary>Specify when the class will <em>end</em> on scheduled days. Format: 'HH:mm:ss'</summary>\n        <br>\n        <p>This ending time applies to all scheduled days, and must be after the start time.</p>\n        <p>If you would like to specify an additional recurring timeslot, you must create another class for this studio.</p>\n        </details>\n    ")),
                ('schedule', recurrence.fields.RecurrenceField(help_text='\n        <details>\n        <summary>Specify which day(s) this class will occur on.</summary>\n        <p>You can add a rule for reoccurrences as well as exceptions to those rules by clicking "Add rule".</p>\n        <p>You can also schedule or skip individual dates by clicking "Add date".</p>\n        </details>\n    ')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='studios.studio')),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cancelled', models.BooleanField(default=False)),
                ('special', models.BooleanField(default=True)),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='classes.class')),
            ],
        ),
    ]
